server:
  port: 9000
spring:
  application:
    name: cloud-gateway-server
  cloud:
    gateway:
      routes:
        - id: service-product-router
          uri: lb://service-product
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: service-order-router
          uri: lb://service-order
          predicates:
              - Path=/order/**
          filters:
              - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhostEurekaA:9300/eureka/,http://localhostEurekaB:9301/eureka/
  instance:
        #使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
    prefer-ip-address: true
        #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:1.0-SNAPSHOT
